/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 34;
  /** RegularExpression Id. */
  int POSDIGIT = 35;
  /** RegularExpression Id. */
  int ZERO = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int IDENT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\";\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"return\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"boolean\"",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 32>",
    "<token of kind 33>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
