#!/bin/bash
make
for i in tests/test???
do
  echo -n "$i: "
  java Parser < $i > $i.out
  if [ ! -r $i.out ];
  then
    echo "FAILED - no output"
  else
    diff $i.ref $i.out > $i.diff
    if [ -s $i.diff ];
    then
      echo "FAILED"
      cat $i.diff
      echo ""
    else
      echo "PASSED"
    fi
  fi
done
